name: Ursa CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  SODIUM_BUILD_STATIC: 1

jobs:
  Build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        workdir: [ ".", "./libursa" ]

    steps:
    - uses: actions/checkout@v3

    - name: Build
      working-directory: ${{ matrix.workdir }}
      run: cargo build --verbose
      if: always()

    - name: Format
      working-directory: ${{ matrix.workdir }}
      run: cargo fmt --all -- --check
      if: always()

    - name: Docs
      working-directory: ${{ matrix.workdir }}
      run: cargo doc --no-deps
      if: always()

    - name: Clippy
      working-directory: ${{ matrix.workdir }}
      run: cargo clippy --all -- -W clippy::not_unsafe_ptr_arg_deref -A clippy::many_single_char_names
      if: always()

    - name: Check
      working-directory: ${{ matrix.workdir }}
      run: cargo check
      if: always()

    - name: Tests
      working-directory: ${{ matrix.workdir }}
      run: cargo test --release
      if: always()

#    - name: Audit
#      working-directory: ${{ matrix.workdir }}
#      run: cargo audit
#      if: always()
